In [1]:
from ailib import Net
import numpy as np
import matplotlib.pyplot as plt

In [2]:
net = Net(shape=[2, 1])

In [3]:
print(net.weights[0].shape, net.biases[0].shape)

(1, 2) (1,)


In [4]:
# net.weights[0] = np.array([[3.0, 3.0]])

# net.biases[0] = np.array([2.0])

In [5]:
print(net.weights[0],'\n\n', net.biases[0])

[[-0.17108748  0.29835571]] 

 [0.]


In [6]:
# np.dot(np.array([[3.0],
#                  [3.0]]).T, np.array([-2, -3]))

In [7]:
net.predict(np.array([-2, -3]))

(array([-0.55289216]), [array([-2, -3]), array([-0.55289216])])

In [8]:
X_train = np.array([[-2, -3],
                     [0,  0],
                     [0,  1],
                     [21, 3],
                     [1, 7],
                     [3, 4],
                     [32, 21],
                     [12, -74]])
                     
y_train = np.sum(X_train*3, axis=1)+2 # y = x1*3 + 2
# y_train[0] = -10
print(X_train,'\n\n', y_train)

[[ -2  -3]
 [  0   0]
 [  0   1]
 [ 21   3]
 [  1   7]
 [  3   4]
 [ 32  21]
 [ 12 -74]] 

 [ -13    2    5   74   26   23  161 -184]


In [9]:
net.compute_cost(X_train, y_train)

np.float64(3647.9211297769307)

In [12]:
J_history = net.gradient_descent(X_train, y_train)

Iteration         0: Cost 3539.700679
Iteration      5000: Cost 3539.700679
Iteration     10000: Cost 3539.700679
Iteration     15000: Cost 3539.700679
Iteration     20000: Cost 3539.700679
Iteration     25000: Cost 3539.700679
Iteration     30000: Cost 3539.700679
Iteration     35000: Cost 3539.700679
Iteration     40000: Cost 3539.700679
Iteration     45000: Cost 3539.700679
Iteration     50000: Cost 3539.700679
Iteration     55000: Cost 3539.700679
Iteration     60000: Cost 3539.700679
Iteration     65000: Cost 3539.700679
Iteration     70000: Cost 3539.700679
Iteration     75000: Cost 3539.700679
Iteration     80000: Cost 3539.700679
Iteration     85000: Cost 3539.700679
Iteration     90000: Cost 3539.700679
Iteration     95000: Cost 3539.700679


In [11]:
# for j in range(len(net.shape)-2, -1, -1):
#     print(j)

_, activations = net.predict(X_train[0])
y_label = y_train[0]
activations.append(y_label)

for j in range(len(net.shape)-2, -1, -1):
    print(X_train[0]*(activations[0] - activations[0+1])/X_train.shape[0])

# print(activations)

[4.03959271 6.43438907]
